/**
 * Sanitiser for blog post HTML.
 *
 * Post bodies are generated by a language model and then rendered with
 * `v-html`, which executes whatever it is given. Nothing sanitised that path.
 *
 * The risk is not hypothetical hand-waving: the focal point that seeds the
 * prompt is now partly model-authored itself (generateBlog proposes next
 * week's topic, and the reroll endpoint writes suggestions straight into the
 * plan). That is a loop where model output becomes model input, so a single
 * successful injection could persist into a published page.
 *
 * Rather than trust the prompt's "use only these tags" instruction, this
 * enforces it. The allowlist matches exactly what the prompt asks for.
 *
 * Deliberately strict: all attributes are dropped. Posts do not need classes,
 * styles or ids, and dropping them removes event handlers (onclick, onerror)
 * and `javascript:` URLs as a category rather than one pattern at a time.
 */

/** Tags the blog prompt is allowed to emit. Anything else is unwrapped. */
const ALLOWED = new Set([
  'h2', 'h3', 'h4',
  'p', 'br',
  'ul', 'ol', 'li',
  'strong', 'em', 'b', 'i',
  'blockquote', 'code', 'pre',
])

/** Elements whose *contents* must go too, not just their tags. */
const DROP_WITH_CONTENT = ['script', 'style', 'iframe', 'object', 'embed', 'noscript', 'template', 'svg', 'math']

export function sanitizePostHtml(input: string): string {
  if (!input) return ''

  let html = input

  // 1. Remove dangerous elements along with everything inside them. Unclosed
  //    variants are handled by the tag pass below.
  for (const tag of DROP_WITH_CONTENT) {
    html = html.replace(new RegExp(`<${tag}\\b[\\s\\S]*?<\\/${tag}\\s*>`, 'gi'), '')
    html = html.replace(new RegExp(`<${tag}\\b[^>]*>`, 'gi'), '')
  }

  // 2. Strip comments — they can hide conditional-comment payloads.
  html = html.replace(/<!--[\s\S]*?-->/g, '')

  // 3. Rebuild every remaining tag from its name alone, discarding all
  //    attributes. Unknown tags are unwrapped rather than escaped, so their
  //    text survives while the element does not.
  html = html.replace(/<\/?([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*>/g, (_match, rawName: string, ...rest) => {
    const name = rawName.toLowerCase()
    if (!ALLOWED.has(name)) return ''
    const full = rest[rest.length - 1] as string
    const idx = rest[rest.length - 2] as number
    const isClosing = full.slice(idx, idx + 2) === '</'
    if (isClosing) return `</${name}>`
    return name === 'br' ? '<br>' : `<${name}>`
  })

  return html.trim()
}
